Update users.
ecare-software/ecare-residential pull request #332
Opened 2024-04-26 20:00 UTC by tydangelo18

2024-04-27 16:50 UTC, dkennedy881 requested changes
For this change since just a new page. Could you add screenshots for documentation purposes

2024-04-28 17:01 UTC, tydangelo18 commented
<img width="1478" alt="Screenshot 2024-04-28 at 11 59 24 AM" src="https://github.com/ecare-software/ecare-residential/assets/60044459/642a5c25-abf2-4b77-8c1d-edf575e1c24e">

<img width="562" alt="Screenshot 2024-04-28 at 11 59 34 AM" src="https://github.com/ecare-software/ecare-residential/assets/60044459/98e32edd-8edd-496e-ba47-1a35c6c9c36a">

<img width="930" alt="Screenshot 2024-04-28 at 11 59 45 AM" src="https://github.com/ecare-software/ecare-residential/assets/60044459/47f6f4f9-8216-48dd-9a91-b4ab2cbcb372">

<img width="616" alt="Screenshot 2024-04-28 at 12 00 20 PM" src="https://github.com/ecare-software/ecare-residential/assets/60044459/3c123581-1456-4ea4-9c18-a8bc063cb140">

2024-04-28 17:08 UTC, dkennedy881 commented
@tydangelo18 
Could you center or stretch out the password fields

2024-04-28 17:08 UTC, dkennedy881 approved these changes

2024-04-29 02:07 UTC, merged